### PR TITLE
feat provider: Add support for theme configuration per realm

### PR DESCRIPTION
**Pull request by phillipj**
This adds support for configuring themes per realm. All four themes can be configured specifically:
* Account
* Admin
* Email
* Login

### CODE REVIEW

**Comment by phillipj** [comment]
CI fails:

```
# github.com/hashicorp/terraform/config
../../hashicorp/terraform/config/testing.go:9: t.Helper undefined (type *testing.T has no field or method Helper)
The command "eval go get -t -v ./... " failed. Retrying, 2 of 3.
```

Looks unrelated to these changes?

**Comment by tazjin** [comment]
> Looks unrelated to these changes?

It probably is ... the CI setup does not use the Repeatr-based builds right now, which means that dependencies are essentially unpinned.

**Comment by phillipj** [comment]
Anything I can provide to help you review this? Example output or similar?

**Comment by tazjin** [comment]
The changes look fine to me. There's no easy fix for the CI build, so I'll be merging this in.

**Comment by phillipj** [comment]
@tazjin are you planning to cut a new release with this added feature?

**Comment by tazjin** [comment]
@phillipj I can cut a new RC for this, but I'm still not declaring it a stable release. I'll presumably go back to this project next week and clean up a bit to get to some form of stable!

**Comment by phillipj** [comment]
Ahhh, both sounds great! 👍

**Comment by tazjin** [comment]
@phillipj https://github.com/tazjin/terraform-provider-keycloak/releases/tag/v0.1-rc2 there you go!

**Comment by phillipj** [comment]
Woopwoop thanks for the quick response!

**Pull request merged**
